name: React Tests CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installazione dipendenze
        run: npm ci

      - name: Esecuzione Test
        # CI=true serve a Jest per non attivare la modalità "watch" interattiva sul server
        run: npm test -- --ci --watchAll=false
